@startuml db
skin rose

package "account" {
  entity "users" {
    + id : number
    ==
    email : string : unique
    hashed_password : string
    username : string
    type : enum
    created_at : datetime
    updated_at : datetime
  }

  entity "projects" {
    + id : number
    ==
    # user_id : number
    name : string
    created_at : datetime
    updated_at : datetime
  }

  entity "media" {
    + id
    ==
    # user_id : number
    file_name : string
    file_path : string
    file_type : string
    created_at : datetime
    updated_at : datetime
  }
}

package "site" {
  entity "websites" {
    + id : number
    ==
    # project_id : number
    template : enum
    slug : string : unique
    title : string
    created_at : datetime
    updated_at : datetime
  }

  entity "pages" {
    + id : number
    ==
    # website_id : number
    type : enum
    slug : string
    name : string
    order : number
    status : enum
    created_at : datetime
    updated_at : datetime
  }

  entity "blocks" {
    + id
    ==
    # page_id : number
    type : enum
    content : text
    order : number
    status : enum
    created_at : datetime
    updated_at : datetime
  }

  entity "fonts" {
    + id : number
    ==
    # website_id : number
    role : enum
    url : string
    created_at : datetime
    updated_at : datetime
  }

  entity "colors" {
    + id : number
    ==
    # website_id : number
    role : enum
    hex : string
    created_at : datetime
    updated_at : datetime
  }
}

users --o{ projects
users --o{ media
projects --o{ websites
websites --o{ pages
websites --o{ fonts
websites --o{ colors
pages --o{ blocks
@enduml
