name: Backend CI

on:
  push:
    paths:
      - "backend/**"
    branches:
      - develop
      - main
  pull_request:
    paths:
      - "backend/**"
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      DATABASE_URL: "postgresql://postgresql:password@localhost:5432/db"
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: db
          POSTGRES_USER: postgresql
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: cd backend && npm install

      - name: Run build
        run: cd backend && npm run build

      - run: npm run generate
      - run: npx prisma migrate dev
      - run: npx prisma db seed

      - name: Run tests
        run: cd backend && npm test

      - name: Run lint
        run: cd backend && npm run lint
