name: Backend CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 

    - name: Install dependencies
      run: npm install --prefix ./backend

    - name: Run build
      run: npm run --prefix ./backend build

    - name: Run tests
      run: npm test --prefix ./backend

    - name: Run lint
      run: npm run --prefix ./backend/package.json lint
