name: Backend CI

on:
  push:
    branches:
      - develop
      - main
    paths:
      - "backend/**"
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: cd backend && npm install

      - name: Run build
        run: cd backend && npm run build

      - name: Run tests
        run: npm run generate && cd backend && npm test

      - name: Run lint
        run: cd backend && npm run lint
