name: Frontend CI

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --prefix ./frontend

      - name: Run lint
        run: npm run --prefix ./frontend lint
